### PR TITLE
Implement reversing for iOS 4,5,6,12

### PR DESCRIPTION
**Pull request by dnne**
These commits implement sandbox profile extraction and reversing for iOS versions 4, 5, 6 and 12. Issue #1 should also be fixed by these commits.

Overall changes:
- Sandbox toolkit should not be used anymore. Extraction of sandbox binary profiles and operations will be made using `helpers/extract_sandbox_data.py`. 
- Old versions of iOS use different format for regular expressions. Two new regular expressions parsers have been implemented(version 1 and 2). Each regular expression parser can be found in `reverse-sandbox/regex_parser_v[1-3].py`
- Added filters for each iOS versions. Filters are now separated by version. Each filter can be found in `reverse-sandbox/filters/`.
- Minor changes to `reverse-sandbox/sandbox_regex.py` in order to support different regex versions

### CODE REVIEW

**Comment by dukebarman** [comment]
What about merge?

**Comment by razvand** [comment]
I'm trying to run it on the [iOS 12.4.1 firmware image](https://www.theiphonewiki.com/wiki/PeaceG_16G102_(iPhone6,1)). But I get the following issue:

```
razvan@pr708-drone:~/ios-security/sandblaster.git/helpers$ ./extract_sandbox_data.py -o ../../store/out/sb_ops ../../store/out/iPhone_4.0_64bit_12.4.1_16G102/com.apple.security.sandbox.kext 12.4
Traceback (most recent call last):
  File "./extract_sandbox_data.py", line 433, in <module>
    exit(main(args))
  File "./extract_sandbox_data.py", line 378, in main
    string_tables = extract_string_tables(binary)
  File "./extract_sandbox_data.py", line 180, in extract_string_tables
    binary_get_string_from_address, get_tables_section(binary))
  File "./extract_sandbox_data.py", line 97, in get_tables_section
    str_sect = get_cstring_section(binary)
  File "./extract_sandbox_data.py", line 64, in get_cstring_section
    seg = binary.get_segment('__TEXT')
AttributeError: '_pylief.MachO.Binary' object has no attribute 'get_segment'
```

Is there a problem with my `lief` installation?

```
razvan@pr708-drone:~/ios-security/sandblaster.git/helpers$ pip3 list | grep lief
lief                          0.9.0
```
```

**Comment by dnne** [comment]
@razvand If I remember right you need to run `extract_sandbox_data.py` with kernelcache as binary, instead of sandbox kernel extension for iOS 12. Use `./extract_sandbox_data.py --help` for more info.

I checked again the documentation for [LIEF::MachO::get_segment()](https://lief.quarkslab.com/doc/latest/api/python/macho.html#lief.MachO.Binary.get_segment) and it should work.

You may also try to install pylief using the following resources:
https://github.com/lief-project/LIEF/issues/231#issuecomment-439689716
https://github.com/lief-project/LIEF#downloads--install

**Comment by dukebarman** [comment]
Use dev version of lief `pip install [--user] lief==0.10.0.dev0` (https://github.com/lief-project/LIEF/issues/342). @dnne184's PR works nice with it

**Comment by razvand** [comment]
@dnne184 , it doesn't work. I get the same thing trying to use the kernelcache image file instead of the sandbox extension:

```
razvan@pr708-drone:~/ios-security/sandblaster.git/helpers$ ./extract_sandbox_data.py -o ../../store/out/sb_ops ../../store/out/iPhone_4.0_64bit_12.4.1_16G102/kernelcache.mach.arm 12
.4.1
Traceback (most recent call last):
  File "./extract_sandbox_data.py", line 433, in <module>
    exit(main(args))
  File "./extract_sandbox_data.py", line 378, in main
    string_tables = extract_string_tables(binary)
  File "./extract_sandbox_data.py", line 180, in extract_string_tables
    binary_get_string_from_address, get_tables_section(binary))
  File "./extract_sandbox_data.py", line 97, in get_tables_section
    str_sect = get_cstring_section(binary)
  File "./extract_sandbox_data.py", line 64, in get_cstring_section
    seg = binary.get_segment('__TEXT')
AttributeError: '_pylief.MachO.Binary' object has no attribute 'get_segment'
```

I followed @dukebarman 's advice of installing `lief=0.10.0.dev0` and I get this:

```
razvan@pr708-drone:~/ios-security/sandblaster.git/helpers$ ./extract_sandbox_data.py -o ../../store/out/sb_ops ../../store/out/iPhone_4.0_64bit_12.4.1_16G102/kernelcache.mach.arm 12
.4.1
Traceback (most recent call last):
  File "./extract_sandbox_data.py", line 433, in <module>                                                                                                                                exit(main(args))                                                                                                                                                                   File "./extract_sandbox_data.py", line 378, in main
    string_tables = extract_string_tables(binary)
  File "./extract_sandbox_data.py", line 180, in extract_string_tables
    binary_get_string_from_address, get_tables_section(binary))
  File "./extract_sandbox_data.py", line 105, in get_tables_section
    assert len(sects) >= 1 and all([sects[0] == s for s in sects])
AssertionError
```
iPhone_4.0_64bit_12.0.1_16A404
It may be because of some updates to newer iOS versions (I'm trying iOS 12.4.1). @dnne184 , if you could take a look, I placed the `.ipsw` image file and the kernelcache and sandbox extension I extracted here: http://titan.cs.pub.ro/~razvan/store/ios/iPhone_4.0_64bit_12.4.1_16G102/

**Comment by razvand** [comment]
@dnne184 , I get the same on the error for iOS 12.0.1

```
razvan@pr708-drone:~/ios-security/sandblaster.git/helpers$ ./extract_sandbox_data.py -o ~/ios-security/store/out/iPhone_4.0_64bit_12.0.1_16A404/sb_ops ~/ios-security/store/out/iPhone_4.0_64bit_12.0.1_16A404/kernelcache.mach.arm 12.0.1
Traceback (most recent call last):
  File "./extract_sandbox_data.py", line 433, in <module>
    exit(main(args))
  File "./extract_sandbox_data.py", line 378, in main
    string_tables = extract_string_tables(binary)
  File "./extract_sandbox_data.py", line 180, in extract_string_tables
    binary_get_string_from_address, get_tables_section(binary))
  File "./extract_sandbox_data.py", line 105, in get_tables_section
    assert len(sects) >= 1 and all([sects[0] == s for s in sects])
AssertionError
```

I stored the `.ipsw` and the extracted kernelcache and sandbox extension here: http://titan.cs.pub.ro/~razvan/store/ios/iPhone_4.0_64bit_12.0.1_16A404/

**Comment by razvand** [comment]
@dnne184 , @dukebarman , I made it work. Even for iOS 12 the input is the sandbox extension. The issue was with the lief version. It doesn't work with lief 0.9.0, it worked with lief 0.10.0.dev0 as @dukebarman suggested.

@dnne184 , please update the help message in `extract_sandbox_data.py` to not say that the kernelcache is required for iOS 12. It's still the sandbox extension that needs to be provided as input to the `extract_sandbox_data.py` helper tool, both to extract the sandbox operations and the sandbox bundle. I tested it for iOS 12.4.1 and that's how it works.

**Comment by dukebarman** [comment]
Lief 0.10 was released

**Review by radudum10 — APPROVED** [review]

**Pull request merged**
